version: '3'
services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
  frontend:
    image: node:18
    working_dir: /app/frontend
    volumes:
      - ../frontend:/app/frontend
    command: sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"